CREATE TABLE teams(
	id INT NOT NULL AUTO_INCREMENT,
	gk VARCHAR(50) NOT NULL,
	rb VARCHAR(50) NOT NULL,
	cb1 VARCHAR(50) NOT NULL,
	cb2 VARCHAR(50) NOT NULL,
	lb VARCHAR(50) NOT NULL,
	rm VARCHAR(50) NOT NULL,
	cm1 VARCHAR(50) NOT NULL,
	cm2 VARCHAR(50) NOT NULL,
	lm VARCHAR(50) NOT NULL,
	st1 VARCHAR(50) NOT NULL,
	st2 VARCHAR(50) NOT NULL,
	PRIMARY KEY(id)
);