CREATE TABLE `serie_a` (
	`Pos` VARCHAR(255) NOT NULL DEFAULT '',
	`Team` VARCHAR(255) NOT NULL,
	`Pl` VARCHAR(255) NOT NULL DEFAULT '',
	`W` VARCHAR(255) NOT NULL DEFAULT '',
	`D` VARCHAR(255) NOT NULL DEFAULT '',
	`L` VARCHAR(255) NOT NULL DEFAULT '',
	`F` VARCHAR(255) NOT NULL DEFAULT '',
	`A` VARCHAR(255) NOT NULL DEFAULT '',
	`GD` VARCHAR(255) NOT NULL DEFAULT '',
	`Pts` VARCHAR(255) NOT NULL DEFAULT ''
)
COLLATE='latin1_swedish_ci'
;
